### ISSUE TITLE
Using spark-submit

### ISSUE THREAD

**Issue by cosmincatalin** [bitnami/bitnami-docker-spark#13]
**Description**

The Docker image for spark is just great, but I have found it difficult to use it for submitting jobs using the standard `spark-submit`.

More concretely, if I try to submit a job from the *master* then I would have to overwrite the Docker `CMD` which in turn makes the *master* dumb and stops it from being used in a _cluster_ fashion.

```
services:
    spark-master:
        image: bitnami/spark:3.0.1
        cmd: spark-submit --master spark://spark-master:7077 app.jar
```

The somehow dirty solution I have found is to use a _client_ image, but that one will be too smart for its own good, because of the `ENTRYPOINT`.

```
services
    spark-master:
        image: bitnami/spark:3.0.1
    spark-client:
        image: bitnami/spark:3.0.1
        command: "spark-submit --master spark://spark-master:7077 app.jar"
```

Do you have a solution for this problem?
