### ISSUE TITLE
Class org.apache.hadoop.fs.s3a.S3AFileSystem not found

### ISSUE THREAD

**Issue by christianversloot** [bitnami/bitnami-docker-spark#20]
I've successfully managed to run the Spark 3.0.1 image with this `docker-compose.yml` file:

```
version: '2'

services:
  spark:
    build: .
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
  spark-worker-1:
    build: .
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
```

Here, I'm building the Docker image myself - the only thing that I do differently is installing Python `3.7.1` instead of `3.6.x` because otherwise I would have a mismatch between my Jupyter Notebook and Python running within the Spark containers, e.g. see https://github.com/bitnami/bitnami-docker-spark/issues/18 for more information.

This works and a simple parallelization provides correct results. However, Attempting to read data from S3 by means of S3A gives the following error:

```
# Load data
df = spark.read.format('csv').load('s3a://bucket/data.csv', header='true')

Py4JJavaError: An error occurred while calling o74.load.
: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2197)
```

I searched quite a bit and found the dependencies for S3A to be listed here: https://hadoop.apache.org/docs/current2/hadoop-aws/tools/hadoop-aws/index.html#Dependencies

- hadoop-aws jar.
- aws-java-sdk-s3 jar.
- aws-java-sdk-core jar.
- aws-java-sdk-kms jar.
- joda-time jar; use version 2.8.1 or later.
- httpclient jar.
- Jackson jackson-core, jackson-annotations, jackson-databind jars.

Performing an `exec` in one of the Spark containers and then `ls ./jars`, I can see that all the jars are present with quite recent versions (often, 3.x). The `aws-java-sdk` is available as a `-bundle`, which I assume contains the jars listed above.

This I find strange, because all the jars seem to be present, while I'm getting that error. Did I miss something?
