### ISSUE TITLE
Unable to read local files when using pyspark

### ISSUE THREAD

**Issue by michalbarer** [bitnami/bitnami-docker-spark#23]
Hey!
I use this image to run a spark cluster on my local machine (`docker-compose.yml` is attached below). I use pyspark from outside the containers, and everything is running well, up until I'm trying to read files from a local directory.  I mounted the path to the data inside the containers.

My `docker-compose` file:
```
version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - type: bind
        source: /path/to/data/dir/
        target: /opt/spark/data
  spark-worker-1:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - type: bind
        source: /path/to/data/dir/
        target: /opt/spark/data
  spark-worker-2:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - type: bind
        source: /path/to/data/dir/
        target: /opt/spark/data
```

This is my code:
```
from pyspark.conf import SparkConf
from pyspark.sql import SparkSession

conf = SparkConf()
conf.setAll([
    ('spark.master', 'spark://127.0.0.1:7077'),
    ('spark.app.name', 'test'),
    ('spark.driver.host', '172.19.0.1'),
])

spark = SparkSession.builder.config(conf=conf).getOrCreate()
f = 'file:///opt/spark/data/textual_dump_example.json'  # Here I use the file that is mounted in the containers

df = spark.read.json(f)
df.printSchema()
df.show()
```

The exception I get (even though I checked inside te container and the file does exist) :
```
  File "/home/michal/PycharmProjects/spark-play/test.py", line 22, in <module>
    df = spark.read.json(file)
  File "/home/michal/PycharmProjects/spark-play/venv/lib/python3.6/site-packages/pyspark/sql/readwriter.py", line 300, in json
    return self._df(self._jreader.json(self._spark._sc._jvm.PythonUtils.toSeq(path)))
  File "/home/michal/PycharmProjects/spark-play/venv/lib/python3.6/site-packages/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/michal/PycharmProjects/spark-play/venv/lib/python3.6/site-packages/pyspark/sql/utils.py", line 134, in deco
    raise_from(converted)
  File "<string>", line 3, in raise_from
pyspark.sql.utils.AnalysisException: Path does not exist: file:/opt/spark/data/textual_dump_example.json;
```

and when I change the file to my local path:
```
f = 'file:///path/to/data/dir/textual_dump_example.json'

df = spark.read.json(f)
```

This is the exception I get (not the full stacktrace):
```
Caused by: java.io.FileNotFoundException: File file:/path/to/data/dir/textual_dump_example.json does not exist
It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
```

How should I read files properly?
(If any information is missing, please let me know and I will add it to the issue. I have more logs from the application)

Thank you!

**Comment by miguelaeh** [comment]
Hi @michalbarer ,
I think it could be a permission error. Since this container is non-root, the mounted file should be owned by the user `1001` before mounting it, have you try changing the permissions of your local file?

**Comment by michalbarer** [comment]
@miguelaeh Thank you for your answer.
Should I change the permissions of the local file to `1001:1001`?

**Comment by miguelaeh** [comment]
Hi @michalbarer ,
yes, but only the user to `1001` the group should be `root`

**Comment by zxy-zxy** [comment]
Hello, I do facing the same issue, although I have tried to change the ownership of the file to `1001`.
@michalbarer Have you been able to sort it out?
Thank you!

**Comment by miguelaeh** [comment]
Hi @zxy-zxy ,
Can you explain what you tried and the error you are getting?

**Comment by zxy-zxy** [comment]
Hi @miguelaeh , 
Thank you for your response.
Here is a `docker-compose.yml`

```
spark:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./spark/jars:/opt/bitnami/spark/.ivy2
      - ./data/:/opt/bitnami/spark/spark-data

  spark-worker-1:
    image: docker.io/bitnami/spark:3-debian-10
    ports:
      - '8081:8081'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark/jars:/opt/bitnami/spark/.ivy2           
      - ./data/:/opt/bitnami/spark/spark-data
```
      
My pyspark application

```
from pyspark.sql import SparkSession

SPARK_DATA_PATH = 'file:///opt/bitnami/spark/spark-data'
log_file = f"{SPARK_DATA_PATH}/logs.txt"

spark = (
    SparkSession.builder.appName("ReadLogs")
        .master("spark://0.0.0.0:7077")
        .getOrCreate()
)
spark.sparkContext.setLogLevel('WARN')

log_data = spark.read.text(log_file).cache()

num_ds = log_data.filter(log_data.value.contains("d")).count()
num_ss = log_data.filter(log_data.value.contains("s")).count()

res = f"Lines with d: {num_ds}, lines with s: {num_ss}"
print(res)
```

I am trying to submit the application above from driver (my local machine) to spark cluster which is running under docker-compose. 

Result of the `ls -alh data/logs.txt` : 
`-rw-rw-r-- 1 1001 root 119 Feb 22 01:16 data/logs.txt`

 Here is an error text: 
```
log_data = spark.read.text(log_file).cache()
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 389, in text
  File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 134, in deco
  File "<string>", line 3, in raise_from
pyspark.sql.utils.AnalysisException: Path does not exist: file:/opt/bitnami/spark/spark-data/logs.txt;
```
If I submit application from the inside of the docker container it works without any error.
Looking forward to hear a response from you.
