### ISSUE TITLE
Doesn't work with kubernetes charts with the configmap

### ISSUE THREAD

**Issue by dennybaa** [bitnami/bitnami-docker-spark#26]
When providing custom master configmap:

 16:06:55.76 
 16:06:55.76 Welcome to the Bitnami spark container
 16:06:55.77 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-spark
 16:06:55.77 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-spark/issues
 16:06:55.78 
/opt/bitnami/scripts/spark/entrypoint.sh: line 22: /opt/bitnami/spark/conf/spark-env.sh: Permission denied

The spark-env.sh MUST not be executed. Since working it around in the chart doesn't seem reasonable

aka
```
      initContainers:
        - name: fix-perm
          image: {{ template "spark.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - bash
            - -c
            - cd /cmsrc; cp -r ./ /cmdst; chmod +x /cmdst/spark-env.sh
          volumeMounts:
            {{- if .Values.master.configurationConfigMap }}
            - name: config
              mountPath: cmdst
            - name: config-src
              mountPath: cmsrc
            {{- end }}

        {{- if .Values.master.configurationConfigMap }}
        - name: config
          emptyDir: {}
        - name: config-src
          configMap:
            name: {{ .Values.master.configurationConfigMap }}
        {{- end }}
```
