### ISSUE TITLE
Using remote pySpark session to read parquet file.

### ISSUE THREAD

**Issue by warichet** [bitnami/bitnami-docker-spark#36]
Hello,
i try to use remote session with pyspark.

In my infra i have 3 containers (spark master/spark worker/standard python) 
Spark takes Kafka events as stream and store them in a parquet sink.
```
    check_point_location = "/tmp/edge/check"
    location =  "/tmp/edge/data"
    
    df_edge.writeStream\
        .format("parquet")\
        .option("checkpointLocation", check_point_location)\
        .option("path", location)\
        .option("mode", 'append')\
        .trigger(processingTime='10 seconds')\
        .start()\
        .awaitTermination()
```
The python container read parquet files using a remote pyspark session.
```
    spark = SparkSession.builder\
       .appName('Flask_gunicorn') \
       .master('spark://0.0.0.0:7077') \
       .config('spark.submit.deployMode', 'client') \
       .config('spark.cores.max', '1') \
       .config('spark.executor.memory', '1g') \
       .config('spark.jars.ivy', '/opt/bitnami/spark/ivy') \
       .getOrCreate()
```

I have mount volumes to shared master data with python container.
```
      - master_vertex_data:/tmp/vertex/data
      - master_edge_data:/tmp/edge/data
```
If i not mount the volumes, i have an error type file not found.
pyton container haven't any data / master have meta data/ worker have parquet files.

If a mount them the application that used remote session cound found the master file.
But when a mount volume a lost parquet files in worker side. 
pyton container havehave meta data / master have meta data/ worker haven't data.

I don't understand why i loss parquet files in second case ?
Also i don't know why application wich run on python container needs meta data ? 

Thanks
Sebastien

Configuration:

* spark master
```
 spark:
    build: .
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_DIRS=/tmp
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - master_ivy_jars:/opt/bitnami/spark/ivy:z
      - master_vertex_data:/tmp/vertex/data
      - master_edge_data:/tmp/edge/data
```

* spark worker
```
  spark-worker-1:
    build: .
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_INSTANCES=2
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_DIRS=/tmp
      - SPARK_WORKER_PORT=7078
    volumes:
      - worker1_ivy_jars:/opt/bitnami/spark/ivy:z
```

An other  python:3.9-slim-buster
```
volumes:
  master_vertex_data:
    external: true
  master_edge_data:
    external: true


services:
  flask:
    build: .
    network_mode: host
    volumes:
      - master_vertex_data:/tmp/master/vertex/data
      - master_edge_data:/tmp/master/edge/data
```
