### ISSUE TITLE
How to read local csv

### ISSUE THREAD

**Issue by dfaustryjak** [bitnami/bitnami-docker-spark#37]
Hey

I have following config for spark:

```
version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3.1.1
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./data/:/opt/bitnami/spark/input_data/
  spark-worker-1:
    image: docker.io/bitnami/spark:3.1.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./data/:/opt/bitnami/spark/input_data/
  spark-worker-2:
    image: docker.io/bitnami/spark:3.1.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./data/:/opt/bitnami/spark/input_data/
```

And i am trying to load data in following way:

```
conf = pyspark.SparkConf()
conf.setMaster('spark://127.0.0.1:7077')

sc = pyspark.SparkContext(conf=conf)
spark = SparkSession(sc)

df = spark.read.csv("file:///input_data/df_res_merged.csv", header='true')
```
And i hav info that 
```
Path does not exist: file:/input_data/df_res_merged.csv
```
File is located and mounted correctly, each container have this file
Can you help me resolve this problem I tried few combinations of path full etc. but it doesn't work..
