### ISSUE TITLE
Four-node bitnami cluster on a single "bare-metal" computer (e.g. laptop). How to configure a shared directory for Spark on the "bare-metal" server ...

### ISSUE THREAD

**Issue by nmvega** [bitnami/bitnami-docker-spark#39]
Dear `Binami` Friends:

I'm running the following `bitnami` cluster on a `single computer `(pretty plain vanilla). What does one do for a `shared filesystem / directory` in this deployment case? Perhaps mapping all `workers` to a common underlying `docker volume`? I know how to map `docker volumes`, and if that indeed is the solution, might you be so kind as to modify the below for me, just so that I'm clear (because I suspect there might be `conf` changes needed, too).

Of if it's something else entirely, please let me know the steps to implement that.

`Thank you!` `=:)`

```
version: '3'

networks:
  myNet:
    name: myNet
    external: false
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.10.0/24
         gateway: 192.168.10.1

services:
  spark:
    image: docker.io/bitnami/spark:latest
    hostname: spark
    container_name: spark
    restart: always
    depends_on:
      - spark-worker01
      - spark-worker02
      - spark-worker03
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      myNet:
        ipv4_address: 192.168.10.10

  spark-worker01:
    image: docker.io/bitnami/spark:latest
    hostname: worker01
    container_name: worker01
    restart: always
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=8
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      myNet:
        ipv4_address: 192.168.10.11

  spark-worker02:
    image: docker.io/bitnami/spark:latest
    hostname: worker02
    container_name: worker02
    restart: always
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=8
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      myNet:
        ipv4_address: 192.168.10.12

  spark-worker03:
    image: docker.io/bitnami/spark:latest
    hostname: worker03
    container_name: worker03
    restart: always
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=8
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      myNet:
        ipv4_address: 192.168.10.13
```
