### ISSUE TITLE
How to connect to spark with started with docker compose

### ISSUE THREAD

**Issue by tanduong** [bitnami/bitnami-docker-spark#5]
**Description**

This is a beginner question.

I started spark with docker-compose file as in this project and I can run spark-shell within spark service. But I don't know how to connect to it with pyspark.

Here is the docker compose file that I used (added expose port 7077 of master):

```
version: "2"

services:
  spark:
    image: docker.io/bitnami/spark:2-debian-10
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker-1:
    image: docker.io/bitnami/spark:2-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    image: docker.io/bitnami/spark:2-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
```

And here is python code that I used in my local machine

```
import pyspark

# sc = pyspark.SparkContext(master="spark://spark:7077", appName="maps_and_lazy_evaluation_example")

# sc = pyspark.SparkContext(master="local", appName="maps_and_lazy_evaluation_example")

sc = pyspark.SparkContext(master="spark://e54f9770e914:7077")
```

`e54f9770e914` and `spark` are already in /etc/hosts file and mapped to 127.0.0.1.

The connection just timed out.
I can however do: 

```
telnet cd898ee0e1a3 7077
```

And I saw that DNS resolved properly for telnet command.

Could you please help guide me in the right direction?

**Comment by juan131** [comment]
Hi @tanduong 

In theory, you don't need to edit the `/etc/hosts`, nor access Spark using its Docker hostname. I mean, you can simply configure your code so it looks like this:

```pyton
sc = pyspark.SparkContext(master="spark://127.0.0.1:7077", appName="maps_and_lazy_evaluation_example")
```

**Comment by tanduong** [comment]
Hi @juan131,

I tried that and it just waits till timed out. Later I found out (by having a notebook service run with docker compose) that my pyspark is running on python 3.7 and the worker is running python 3.6 so it doesn't match. I am using https://github.com/jupyter/docker-stacks and not seeing an easy wait to force python 3.6 for the notebook or force python 3.7 for the worker (there is no way to specify python version  know of using bitnami-docker-spark).

**Comment by juan131** [comment]
Hi @tanduong 

Regarding the Python version, I'm afraid that we don't offer different branches for Spark depending on Python. As you can see in the link below, it uses Python 3.6:

- https://github.com/bitnami/bitnami-docker-spark/blob/master/2/debian-10/Dockerfile#L13

Regarding the issue connecting to the master. Could you try using the Docker Compose below:

```yaml
version: "2"

services:
  spark:
    image: docker.io/bitnami/spark:2-debian-10
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker-1:
    image: docker.io/bitnami/spark:2-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    image: docker.io/bitnami/spark:2-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-client:
    image: docker.io/bitnami/spark:2-debian-10
    entrypoint:
      - sleep
      - infinity
```

Then, you can use the `spark-client` container as shown below:

```console
$ docker-compose up -d
$ docker-compose exec spark-worker-2 bash
I have no name!@ab6f1939534a:/opt/bitnami/spark$ 
```

That client container can use `spark` as the hostname to use to connect to the master node.

**Comment by nmvega** [comment]
Hello Friends:

Using the following `docker-compose.yml` file, I brought up the `bitnami` `Spark` cluster:

```
version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
  spark-worker-1:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=6
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=6
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
```

Here it is running:
```
user@vps00$ docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                            NAMES
9311b51f7407        bitnami/spark:3-debian-10   "/opt/bitnami/script…"   19 minutes ago      Up 19 minutes                                                        sparkd_spark-worker-1_1
4da7b6fd5fe0        bitnami/spark:3-debian-10   "/opt/bitnami/script…"   19 minutes ago      Up 19 minutes                                                        sparkd_spark-worker-2_1
6ae0f7e77913        bitnami/spark:3-debian-10   "/opt/bitnami/script…"   19 minutes ago      Up 19 minutes       0.0.0.0:7077->7077/tcp, 0.0.0.0:8080->8080/tcp   sparkd_spark_1
```

And the `UI` indicates this:
```
URL: spark://6ae0f7e77913:7077
Alive Workers: 2
Cores in use: 12 Total, 0 Used
Memory in use: 8.0 GiB Total, 0.0 B Used
Resources in use:
Applications: 0 Running, 2 Completed
Drivers: 0 Running, 0 Completed
Status: ALIVE
```

On the `UNIX CLI` I'm using using `PySpark v3.0.1`

```
user@vps00$ pyspark --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.0.1
      /_/
                        
Using Scala version 2.12.10, OpenJDK 64-Bit Server VM, 1.8.0_262
Branch HEAD
Compiled by user ubuntu on 2020-08-28T07:36:48Z
Revision 2b147c4cd50da32fe2b4167f97c8142102a0510d
Url https://gitbox.apache.org/repos/asf/spark.git
Type --help for more information.
```

Why doesn't this small `Python` snippet -- `startSpark.py` -- work? (see further below)
It seems like something is not communicating correctly.
```
import sys, os
from pyspark.conf import SparkConf
from pyspark.sql import SparkSession, Catalog
from pyspark.sql import DataFrame, DataFrameStatFunctions, DataFrameNaFunctions
from pyspark.sql import functions as F
from pyspark.sql import types as T
from pyspark.sql.types import Row

spark_conf = SparkConf()
spark_conf.setAll([
    ('spark.master', 'spark://vps00:7077'),
    ('spark.app.name', 'myApp'),
    ('spark.submit.deployMode', 'client'),
    ('spark.ui.showConsoleProgress', 'true'),
    ('spark.eventLog.enabled', 'false'),
    ('spark.logConf', 'false'),
    ('spark.driver.bindAddress', 'vps00'),
    ('spark.driver.host', 'vps00'),
])
 
spark_sess          = SparkSession.builder.config(conf=spark_conf).getOrCreate()
spark_ctxt          = spark_sess.sparkContext
spark_reader        = spark_sess.read
spark_streamReader  = spark_sess.readStream
spark_ctxt.setLogLevel("WARN")

myDF  = spark_sess.createDataFrame([Row(col0=0, col1=1, col2=2),
                                    Row(col0=3, col1=1, col2=5),
                                    Row(col0=6, col1=2, col2=8)])
                                    
myGDF = myDF.select('*').groupBy('col1')
myDF.createOrReplaceTempView('mydf_as_sqltable')
print(myDF.collect())
myGDF.sum().show()
#
spark_sess.stop(); quit()
```

`user@vps00$ python -i ./startSpark.py`

```
20/09/28 16:45:44 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
20/09/28 16:45:45 WARN SparkContext: Please ensure that the number of slots available on your executors is limited by the number of cores to task cpus and not another custom resource. If cores is not the limiting resource then dynamic allocation will not work properly!
20/09/28 16:46:05 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/09/28 16:46:20 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[ ... REPEATS ... ]
```

For now, the client and docker services are on the same host (for troubleshooting), but they won't necessarily be. Can someone show me what to adjust above to get it to work in this context?

Thank you in advance!
