### ISSUE TITLE
Cannot get Hadoop 2.7 running with Spark 3.2.0

### ISSUE THREAD

**Issue by cwurld** [bitnami/bitnami-docker-spark#55]
I am following the instructions here: https://github.com/bitnami/bitnami-docker-spark#using-a-different-version-of-hadoop-jars change the Hadoop version to 2.7. But when I run the pyspark commmand to get the Hadoop version 3.3.1

Here is my Dockerfile:

```
FROM bitnami/spark:3.2.0

USER root
RUN rm -r /opt/bitnami/spark/jars && \
    curl --location https://dlcdn.apache.org/spark/spark-3.2.0/spark-3.2.0-bin-hadoop2.7.tgz | \
    tar --extract --gzip --strip=1 --directory /opt/bitnami/spark/ spark-3.2.0-bin-hadoop2.7/jars/
USER 1001
```
Here is my docker-compose file:

```
version: '3'

services:
  spark-master:
    build: .
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master

  spark-worker-1:
    build: .
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER_URK=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_MODE=worker
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
```

Also when I inspect the dir /opt/bitnami/spark/jars in the container, I see a lot of jars for Hadoop 2.7.4.

Not sure this matters, but when I run my python code, I see:

WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Thanks!
